function Hd = Max_Flat_matlab(N, Fc)
%MAX_FLAT_MATLAB Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 13-Feb-2019 08:58:22

% FIR maximally flat Lowpass filter designed using the MAXFLAT function.

% All frequency values are normalized to 1.

% N  = 64;   % Order
% Fc = 0.5;  % Cutoff Frequency

%% Calculate the second-order sections coefficients to avoid round-off
%errors.
[b,a,b1,b2,sos_var,g] = maxflat(N, 'sym', Fc);
Hd                    = dfilt.df2sos(sos_var, g);

% [EOF]
