% Generating RRC filter

Nsamp = 8;           % Filter span
roll_off = 0.35;     % Roll-off factor
sampsPerSymb = 8;    % Uspample/decimation factor

rrcTxFil = comm.RaisedCosineReceiveFilter( ...
  'Shape',                  'Square root', ...
  'RolloffFactor',          roll_off,      ...
  'FilterSpanInSymbols',    Nsym,          ...
  'InputSamplesPerSymbol',  sampsPerSymb,  ...
  'DecimationFactor',       sampsPerSymb   ...
);


fvtool(rrcTxFil, 'Analysis', 'impulse');

