function Hd = Equirippple_Remez_matlab(Fs, N, Fpass, ...
    Fstop, Wpass, Wstop, dens)
%EQUIRIPPPLE_REMEZ_MATLAB Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 05-Feb-2019 11:51:08

% Equiripple Lowpass filter designed using the FIRPM function.

% ##### All frequency values are in kHz.#####
% Fs = 144;  % Sampling Frequency

% N     = 96;    % Order
% Fpass = 11;    % Passband Frequency
% Fstop = 13.5;  % Stopband Frequency
% Wpass = 1;     % Passband Weight
% Wstop = 60;    % Stopband Weight
% dens  = 16;    % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
    {dens});
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
