function Hd = RRC_matlab(Fs, N, Fc, TM, R, DT, Beta)
%RRC_MATLAB Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 05-Feb-2019 12:01:23

% FIR Window Raised-cosine filter designed using the FIRRCOS function.

% All frequency values are in kHz.
% Fs = 144;  % Sampling Frequency
% 
% N    = 96;         % Order
% Fc   = 9;          % Cutoff Frequency
% TM   = 'Rolloff';  % Transition Mode
% R    = 0.35;       % Rolloff
% DT   = 'sqrt';     % Design Type
% Beta = 0.5;        % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = firrcos(N, Fc/(Fs/2), R, 2, TM, DT, [], win);
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
